function fun(app, createCallbackFcn)
  segmentation_plugins = {'spotA','seed_based_watershedA'};

  % Setup
  if isempty(app.segmentation.tabgp)
    app.segmentation.tabgp = uitabgroup(app.Tab_Segment,'Position',[17,20,803,477]);
  end
  tabgp = app.segmentation.tabgp;
  seg_num = length(tabgp.Children)+1;

  % Create new tab
  tab = uitab(tabgp,'Title',sprintf('Segment %i',seg_num), ...
    'BackgroundColor', [1 1 1]);
  app.segment{seg_num}.tab = tab;

  % Create algorithm selection dropdown box
  Callback = @(app, event) changed_SegmentationAlgorithm(app, seg_num, createCallbackFcn);
  app.segment{seg_num}.AlgorithmDropDown = uidropdown(tab, ...
    'Items', segmentation_plugins, ...
    'ValueChangedFcn', createCallbackFcn(app, Callback, true), ...
    'Position', [162,360,200,22]);
  label = uilabel(tab, ...
    'Text', 'Algorithm', ...
    'Position', [90,365,57,15]);

  % Segment name edit field
  function CallbackSegmentNameChange_(app, event)
    CallbackSegmentNameChange(app, seg_num);
  end
  app.segment{seg_num}.Name = uieditfield(tab, ...
    'Value', '', ...
    'ValueChangedFcn', createCallbackFcn(app, @CallbackSegmentNameChange_, true), ...
    'Position', [162,327,200,22]);
  label = uilabel(tab, ...
    'Text', 'Segment Name', ...
    'Position', [57,332,90,15]);

  % Create Titles
  label = uilabel(tab, ...
    'Text', 'Details', ...
    'FontName', 'Yu Gothic UI Light', ...
    'FontSize', 28, ...
    'Position', [70,396,218,41]);

  label = uilabel(tab, ...
    'Text', 'Parameters', ...
    'FontName', 'Yu Gothic UI Light', ...
    'FontSize', 28, ...
    'Position', [480,396,218,41]);


  % Switch to new tab
  app.segmentation.tabgp.SelectedTab = app.segment{seg_num}.tab;

  % Populate GUI components in new tab
  app.segment{seg_num}.AlgorithmDropDown.ValueChangedFcn(app, 'Update');

end
