function [S] = txt_update
    % Creates a textbox.
    S.fh = figure('units','pixels',...
        'position',[40 40 800 800],...
        'menubar','none',...
        'resize','off',...
        'numbertitle','off',...
        'name','Program Log');
    % Empty text control
    S.tx = uicontrol('style','edit',...
        'position',[6 2 550 410],...
        'String', {},...
        'backgroundcolor','w',...
        'HorizontalAlign','left',...
        'min',0,'max',10,...
        'enable','inactive');
    set(S.tx, 'Units', 'normalized');
end